### ISSUE TITLE
rangeFilter with rgxp=datim

### ISSUE THREAD

**Issue by fiedsch** [codefog/contao-haste#84] opened 2016-05-02 13:29 UTC
Haste\Dca\DateRangeFilter::createDatepickerInputField() honors 'time' or 'datim' rgxp and creates the correct date picker, but in validateAndGetTstamp() which is called in filterRecords() you only seem to get the timestamp for the start or end of day respectively, i.e. the time part is dropped. This renders the timepicker part useless.

**Comment by qzminski** [comment] 2016-05-03 07:40
@Toflar is it intended behavior?

**Comment by Toflar** [comment] 2016-05-03 07:52
How can this be intended? Obviously this is a bug :)

**Comment by qzminski** [comment] 2016-05-23 08:12
Fixed in 569f59b.

**Closed by qzminski** 2016-05-23 08:12 UTC
Labels: bug
